import time
import feedparser
from feedgen.feed import FeedGenerator

url_list = [
    "https://bangumi.moe/rss/latest",
    "https://mikanani.me/RSS/Classic",
    "https://acg.rip/.xml",
    "https://share.dmhy.org/topics/rss/rss.xml",
    "https://nyaa.si/?page=rss"
]

rss_feeds = {}

# 读取 url_list 中的 RSS feeds
for i in range(len(url_list)):
    rss_feeds[i] = feedparser.parse(url_list[i])

# 新建一个 feed 生成器
new_feed = FeedGenerator()

# 生成 channel 中的元数据
new_feed.id("Bangumi")
new_feed.title('KookaburraNode233')
new_feed.link(href='https://jp.keepnaive233.network/Bangumi.xml', rel='self', type="application/rss+xml")
new_feed.description('A RSS feed merged Multiple Bangumi RSS feeds generated by KookaburraNode233')
new_feed.logo('https://blog.keepnaive233.network/assets/img/favicons/favicon.ico')
new_feed.ttl('600')

# 针对 bangumi.moe 的 entries 的添加
for i in range(len(rss_feeds[0]['entries'])):
    new_feed_entries = new_feed.add_entry(order='append')
    new_feed_entries.title(rss_feeds[0]['entries'][i]['title'])
    new_feed_entries.description(rss_feeds[0]['entries'][i]['summary'])
    new_feed_entries.link(href=rss_feeds[0]['entries'][i]['link'], rel="alternate", type="text/html")
    new_feed_entries.enclosure(url=rss_feeds[0]['entries'][i]['links'][1]['href'], type="application/x-bittorrent")
    new_feed_entries.id(rss_feeds[0]['entries'][i]['id'])

    asctime_time=time.strftime("%a %b %d %H:%M:%S %Y", rss_feeds[0]['entries'][i]['published_parsed'])
    new_feed_entries.published(asctime_time + " UTC")

# 针对 mikanani.me 的 entries 的添加
for i in range(len(rss_feeds[1]['entries'])):
    new_feed_entries = new_feed.add_entry(order='append')
    new_feed_entries.title(rss_feeds[1]['entries'][i]['title'])
    new_feed_entries.description(rss_feeds[1]['entries'][i]['summary'])
    new_feed_entries.link(href=rss_feeds[1]['entries'][i]['link'], rel="alternate", type="text/html")
    new_feed_entries.enclosure(url=rss_feeds[1]['entries'][i]['links'][2]['href'], type="application/x-bittorrent")
    new_feed_entries.id(rss_feeds[1]['entries'][i]['id'])

    asctime_time=time.strftime("%a %b %d %H:%M:%S %Y", rss_feeds[1]['entries'][i]['published_parsed'])
    new_feed_entries.published(asctime_time + " UTC-8")

# 针对 acg.rip 的 entries 的添加
for i in range(len(rss_feeds[2]['entries'])):
    new_feed_entries = new_feed.add_entry(order='append')
    new_feed_entries.title(rss_feeds[2]['entries'][i]['title'])
    new_feed_entries.description(rss_feeds[2]['entries'][i]['summary'])
    new_feed_entries.link(href=rss_feeds[2]['entries'][i]['link'], rel="alternate", type="text/html")
    new_feed_entries.enclosure(url=rss_feeds[2]['entries'][i]['links'][1]['href'], type="application/x-bittorrent")
    new_feed_entries.id(rss_feeds[2]['entries'][i]['id'])

    asctime_time=time.strftime("%a %b %d %H:%M:%S %Y", rss_feeds[2]['entries'][i]['published_parsed'])
    new_feed_entries.published(asctime_time + " UTC+8")

# 针对 share.dmhy.org 的 entries 的添加
for i in range(len(rss_feeds[3]['entries'])):
    new_feed_entries = new_feed.add_entry(order='append')
    new_feed_entries.title(rss_feeds[3]['entries'][i]['title'])
    new_feed_entries.description(rss_feeds[3]['entries'][i]['summary'])
    new_feed_entries.link(href=rss_feeds[3]['entries'][i]['link'], rel="alternate", type="text/html")
    new_feed_entries.enclosure(url=rss_feeds[3]['entries'][i]['links'][1]['href'], type="application/x-bittorrent")
    new_feed_entries.id(rss_feeds[3]['entries'][i]['id'])

    asctime_time=time.strftime("%a %b %d %H:%M:%S %Y", rss_feeds[3]['entries'][i]['published_parsed'])
    new_feed_entries.published(asctime_time + " UTC+8")

# 针对 nyaa.si 的 entries 的添加
for i in range(len(rss_feeds[4]['entries'])):
    new_feed_entries = new_feed.add_entry(order='append')
    new_feed_entries.title(rss_feeds[4]['entries'][i]['title'])
    new_feed_entries.description(rss_feeds[4]['entries'][i]['summary'])
    new_feed_entries.link(href=rss_feeds[4]['entries'][i]['link'], rel="alternate", type="text/html")
    new_feed_entries.enclosure(url=rss_feeds[4]['entries'][i]['links'][0]['href'], type="application/x-bittorrent")
    new_feed_entries.id(rss_feeds[4]['entries'][i]['id'])

    asctime_time=time.strftime("%a %b %d %H:%M:%S %Y", rss_feeds[4]['entries'][i]['published_parsed'])
    new_feed_entries.published(asctime_time + " UTC")

new_feed.rss_file('rss.xml')
